#!/usr/bin/env bash
###############################################################################
# gittool install script
#
# Installs the scripts under a chosen prefix and creates a "gt" wrapper in <prefix>/bin.
# Works on macOS and Linux. Requires: bash, cp, mkdir, grep, sed.
#
# Quick usage (installs to /usr/local if writable, otherwise ~/.local):
#   curl -fsSL https://raw.githubusercontent.com/<OWNER>/<REPO>/latest/install.sh | bash
#
# Options:
#   --prefix=DIR     Installation prefix (default: auto-detected)
#   --force          Overwrite existing files
#   --uninstall      Remove an existing installation (same prefix logic)
#   --dry-run        Show actions without performing them
#   -h|--help        Show this help summary
#
# Installed layout:
#   <prefix>/lib/gittool/{gt.sh,git.sh,ssh.sh}
#   <prefix>/bin/gt (wrapper)
#
# Identification marker (for safe uninstall): line containing: GT_INSTALL_WRAPPER_MARKER
###############################################################################
set -euo pipefail

SCRIPT_DIR_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/src"
DEFAULT_PREFIX="/usr/local"

# Decide default prefix: /usr/local if writable; otherwise ~/.local
detect_default_prefix() {
  if [[ -w "$DEFAULT_PREFIX" ]] || sudo -n test -w "$DEFAULT_PREFIX" 2>/dev/null; then
    echo "$DEFAULT_PREFIX"
  else
    echo "$HOME/.local"
  fi
}

PREFIX="$(detect_default_prefix)"
FORCE=0
UNINSTALL=0
DRY_RUN=0

print_help() {
  sed -n '1,50p' "$0" | grep -E '^#( |$)' | sed 's/^# ?//'
}

for arg in "$@"; do
  case "$arg" in
    --prefix=*) PREFIX="${arg#*=}" ;;
    --force) FORCE=1 ;;
    --uninstall) UNINSTALL=1 ;;
    --dry-run) DRY_RUN=1 ;;
    -h|--help) print_help; exit 0 ;;
  *) echo "[ERROR] Unknown option: $arg" >&2; exit 1 ;;
  esac
done

LIB_DIR="$PREFIX/lib/gittool"
BIN_DIR="$PREFIX/bin"
WRAPPER="$BIN_DIR/gt"

announce() { echo "==> $*"; }
do_cmd() { if (( DRY_RUN )); then echo "DRY: $*"; else eval "$@"; fi }

ensure_dirs() {
  announce "Creating directories ($LIB_DIR, $BIN_DIR)"
  do_cmd "mkdir -p '$LIB_DIR'"
  do_cmd "mkdir -p '$BIN_DIR'"
}

install_files() {
  announce "Copying scripts to $LIB_DIR"
  for f in gt.sh git.sh ssh.sh; do
    if [[ ! -f "$SCRIPT_DIR_SRC/$f" ]]; then
  echo "[ERROR] Source file not found: $SCRIPT_DIR_SRC/$f" >&2; exit 1
    fi
    if [[ -f "$LIB_DIR/$f" && $FORCE -ne 1 ]]; then
  echo "[ERROR] $LIB_DIR/$f already exists (use --force to overwrite)" >&2; exit 1
    fi
    do_cmd "cp '$SCRIPT_DIR_SRC/$f' '$LIB_DIR/$f'"
    do_cmd "chmod 0755 '$LIB_DIR/$f'"
  done
}

create_wrapper() {
  announce "Creating wrapper $WRAPPER"
  if [[ -f "$WRAPPER" && $FORCE -ne 1 ]]; then
  # If it's already our wrapper, allow silent overwrite
    if grep -q 'GT_INSTALL_WRAPPER_MARKER' "$WRAPPER" 2>/dev/null; then
      :
    else
  echo "[ERROR] $WRAPPER already exists and does not look like this project (use --force to overwrite)" >&2; exit 1
    fi
  fi
  local tmp_file
  tmp_file="$(mktemp)"
  cat > "$tmp_file" <<'EOF'
#!/usr/bin/env bash
# GT_INSTALL_WRAPPER_MARKER
# Wrapper generated by gittool install.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../lib/gittool" && pwd)"
exec bash "$SCRIPT_DIR/gt.sh" "$@"
EOF
  do_cmd "mv '$tmp_file' '$WRAPPER'"
  do_cmd "chmod 0755 '$WRAPPER'"
}

perform_install() {
  ensure_dirs
  install_files
  create_wrapper
  announce "Installation complete. Add $BIN_DIR to your PATH if it isn't already."
  if ! command -v gt >/dev/null 2>&1; then
  echo "[INFO] Open a new shell or export PATH:\n  export PATH=\"$BIN_DIR:\$PATH\""
  fi
}

perform_uninstall() {
  announce "Removing installation at $PREFIX"
  if [[ -f "$WRAPPER" ]] && grep -q 'GT_INSTALL_WRAPPER_MARKER' "$WRAPPER" 2>/dev/null; then
    do_cmd "rm -f '$WRAPPER'"
  announce "Removed wrapper: $WRAPPER"
  else
  echo "[WARNING] Wrapper not found or not recognized as this project: $WRAPPER" >&2
  fi
  if [[ -d "$LIB_DIR" ]]; then
    do_cmd "rm -rf '$LIB_DIR'"
  announce "Removed directory: $LIB_DIR"
  else
  echo "[WARNING] Directory not found: $LIB_DIR" >&2
  fi
  announce "Uninstall complete."
}

main() {
  if (( UNINSTALL )); then
    perform_uninstall
    return 0
  fi
  perform_install
}

main "$@"
